const PRODUCT_ACTION_TYPES = {
  GET_PRODUCTS_START: 'product/GET_PRODUCTS_START',
  GET_PRODUCTS_SUCCESS: 'product/GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED: 'product/GET_PRODUCTS_FAILED',
}
export default PRODUCT_ACTION_TYPES
